config/routes.rb
FindDrug::Application.routes.draw do
  root 'find#drug'
  post 'find/submit', :to => 'find#submit'

end

app/models/find.rb
class Find < ActiveRecord::Base
	validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/find_controller.rb
class FindController < ApplicationController
	def drug
		flash[:page] = 'landing'

		render :drug
	end

	def submit
		@name = drug_params['name']
		if @name != ''
			@drugs = Find.where('name like ?', "%#{@name}%")
			@carriers = {}
			@drugs.each do |drug| 
				if @carriers[drug.carrier]
					@carriers[drug.carrier] << drug
				else
					@carriers[drug.carrier] = [drug]
				end
			end
			flash[:page] = 'results'
		else 
			@drugs = []
		end
		render :submit
	end

	private

	def drug_params
		params.require(:find).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/views/find/drug.html.erb
<div class="page-container">
	<div class="page-container__header">
		<div class="header__icons">

		</div>
	</div>
	<div class="page-container__child">
<div id="logo">
	<svg width="269px" height="100px" viewBox="0 0 197 67" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <!-- Generator: Sketch 3.2.2 (9983) - http://www.bohemiancoding.com/sketch -->
	    <title>Slice 1</title>
	    <desc>Created with Sketch.</desc>
	    <defs></defs>
	    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
	        <rect id="page" stroke="#979797" sketch:type="MSShapeGroup" x="-404" y="-260" width="1037" height="773"></rect>
	        <text id="Medig" sketch:type="MSTextLayer" font-family="Avenir Next" font-size="52" font-weight="260">
	            <tspan x="5" y="47" fill="#0266C8">M</tspan>
	            <tspan x="52.112" y="47" fill="#F90101">e</tspan>
	            <tspan x="81.024" y="47" fill="#F2B50F">d</tspan>
	            <tspan x="113.576" y="47" fill="#00933B">i</tspan>
	            <tspan x="125.328" y="47" fill="#F90101">g</tspan>
	        </text>
	        <g id="tablet" sketch:type="MSLayerGroup" transform="translate(160.000000, 19.000000)">
	            <circle id="Oval-1" fill="#66CFE2" sketch:type="MSShapeGroup" cx="15" cy="15" r="15"></circle>
	            <path d="M5.49066287,23.3013323 L22.575122,5.74557771 L24.7106794,7.94004703 L7.62622027,25.4958016 L5.49066287,23.3013323 L5.49066287,23.3013323 Z" id="Rectangle-5" fill="#FFFFFF" sketch:type="MSShapeGroup"></path>
	        </g>
	    </g>
	</svg>
	<div class="logo__subtitle">
		Search for a <span>prescription drug</span> to find the best provider.
	</div>
</div>


<form action="<%= find_submit_url %>" method="POST">
	<input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

	<!-- <input id="search_bar" name="find[name]" type="text" class="" placeholder="  Search for a shemale..."> -->
	<div id="search-bar">
		<input type="text" name="find[name]" placeholder="Search Drug." id="search-bar__input" />
		<div id="search-bar__input-sibling">
			<div class="icon-mnone"></div>
		</div>
	</div>
</form>
	</div>
</div>


<!-- 

state is mutable 

props is not mutable
 -->

app/views/find/submit.html.erb
<div id="results-page">
<div class="result-page-header">
	<a href="/" id="logo">
		<svg width="135px" height="50px" viewBox="0 0 197 67" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
		    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
		        <rect id="page" stroke="#979797" sketch:type="MSShapeGroup" x="-404" y="-260" width="1037" height="773"></rect>
		        <text id="Medig" sketch:type="MSTextLayer" font-family="Avenir Next" font-size="52" font-weight="260">
		            <tspan x="5" y="47" fill="#0266C8">M</tspan>
		            <tspan x="52.112" y="47" fill="#F90101">e</tspan>
		            <tspan x="81.024" y="47" fill="#F2B50F">d</tspan>
		            <tspan x="113.576" y="47" fill="#00933B">i</tspan>
		            <tspan x="125.328" y="47" fill="#F90101">g</tspan>
		        </text>
		        <g id="tablet" sketch:type="MSLayerGroup" transform="translate(160.000000, 19.000000)">
		            <circle id="Oval-1" fill="#66CFE2" sketch:type="MSShapeGroup" cx="15" cy="15" r="15"></circle>
		            <path d="M5.49066287,23.3013323 L22.575122,5.74557771 L24.7106794,7.94004703 L7.62622027,25.4958016 L5.49066287,23.3013323 L5.49066287,23.3013323 Z" id="Rectangle-5" fill="#FFFFFF" sketch:type="MSShapeGroup"></path>
		        </g>
		    </g>
		</svg>
	</a>
	<form action="<%= find_submit_url %>" method="POST">
		<input
	    type="hidden"
	    name="authenticity_token"
	    value="<%= form_authenticity_token %>">

		<div id="search-bar" class="result-page">
			<input type="text" name="find[name]" id="search-bar__input" placeholder="Search Drug." value="<%= @name %>"/>
			<div id="search-bar__input-sibling">
				<div class="icon-mnone"></div>
			</div>
		</div><span class="icon-search"></span>
	</form>
	<div class="header__icons"></div>
</div>

<div id="results-tabs">
	<div class="results-tab selected">Web</div>
	<div class="results-tab">Images</div>
	<div class="results-tab">Videos</div>

</div>

<div id="results-container">
	<% if !@drugs.empty? %>
		<div>
			<% this = @carriers.count == 1 ? 'This ' : 'These ' %>
			<%= this + @carriers.count.to_s + ' ' + 'result'.pluralize(@carriers.count) %> carry this drug under the following names: (0.1 seconds)
		</div>

		<div class="results-list">
			<% @carriers.each do |carrier, drug_array| %>
			<p>
				<a class="result-list__name" href="https://www.google.com/search?q=<%= carrier %>&btnI=1"><%= carrier.capitalize %></a><br>
				<% drug_array.each do |drug| %>
					&bull; <a class="result-list__carrier" href="https://google.com/search?q=<%= drug.name %>&btnI=1"><%= drug.name.capitalize %></a>, <b><%= drug.brand_or_generic.capitalize %></b> Tier, <%= drug.state %><br>
				<% end %>
			</p>
			<% end %>
		</div>
		

	<% else %>

		Your search - <b><%= @name %></b> - did not match any documents.<br><br>

		Suggestions:<br><br>
		<ul>
			<li>Make sure all words are spelled correctly.</li>
			<li>Try different keywords.</li>
			<li>Try more general keywords.</li>
		</ul>
		
	<% end %>
	</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
       .__ ___.                  __   
_____  |  |\_ |__   ____________/  |_ 
\__  \ |  | | __ \_/ __ \_  __ \   __\
 / __ \|  |_| \_\ \  ___/|  | \/|  |  
(____  /____/___  /\___  >__|   |__|  
     \/         \/     \/            
  Greetings!! Welcome to my site.
  This site was designed and built by me (All Rights Reserved ;) )
  Some tech used are:
  	- Sketch
  	- Icomoon
  	- Ruby on Rails
  	- React
  	- And that's it! The simpler the better am I right?? :)
	-->
<html>
<head>
  <title>Medigo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="results">
	<div id="react-container"></div>
<%= yield %>
</body>
<footer class="<%= flash[:page] %>">
	<a href="#" class="footer-link settings">Settings</a>
	<a href="#" class="footer-link about">About</a>
</footer>
</html>